event_scheduling/config/routes.rb
Rails.application.routes.draw do

get 'users/new'
get "log_out" => "sessions#destroy", :as => "log_out"
get "log_in" => "sessions#new", :as => "log_in"
get "sign_up" => "users#new", :as => "sign_up"
root :to => "welcome#new"
resources :sessions
resources :users do
resources :event_schedules
end
get 'schedule' => "event_schedules#new", :as =>"schedule"
post 'schedule' => 'event_schedules#create', :as =>"schedule_creates"
  get "schedule/list" => "event_schedules#index", :as => 'schedule_list'
get 'schedule/:id/edit' => "event_schedules#edit", :as =>'schedule_edit'

put 'schedule/:id/edit' => "event_schedules#update", :as =>'schedule_update'

end

event_scheduling/app/models/event_schedule.rb
class EventSchedule < ActiveRecord::Base
end

event_scheduling/app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :event
  belongs_to :invitee, class_name: "User"
 
end

event_scheduling/app/models/schedule.rb
class Schedule < ActiveRecord::Base
	 has_many :invitations
   
   has_many :invitees, through: :invitations, foreign_key: :invitee_id
belongs_to :owner,class_name: "User"
end

event_scheduling/app/models/user.rb
class User < ActiveRecord::Base
 
  has_many :events, foreign_key: :owner_id



  
  attr_accessor :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :username
  validates_uniqueness_of :username
  
  def self.authenticate(username, password)
    user = find_by_username(username)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present? 
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

event_scheduling/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

private

def current_user
  @current_user ||= User.find(session[:user_id]) if session[:user_id]
end
end

event_scheduling/app/controllers/event_schedules_controller.rb
class EventSchedulesController < ApplicationController

def new
  @schedule = Schedule.new
  @schedules = Schedule.all
  @users=User.all

end

def create
  # binding.pry
       @schedule=Schedule.new(schedule_params)
        vari = User.find(session[:user_id])
       @schedule.owner_id=vari.id
       @schedule.save
       if params[:invitee_ids]
       params[:invitee_ids].each do |t|
          @invitation=Invitation.new
          @invitation.schedule_id=@schedule.id
          @invitation.invitee_id=t
          @invitation.invited_id=params[:user_id]
          @invitation.save
              end
            end
       redirect_to schedule_path

   end



def index
	@users=User.all
  @schedules=Schedule.all

	end
def show
  @schedule=Schedule.find_by_id(params[:id])
end
def edit
  # binding.pry
  @user=User.all
      @schedule=Schedule.find_by_id(params[:id])
end


  def update
   
    @schedule=Schedule.find_by_id(params[:id])
    # binding.pry
    @schedule.update_attributes(schedule_params)
    redirect_to schedule_path
  end

private

  def schedule_params
  params.require(:schedule).permit(:title,:venue,:date,:time,:description,:status)  
  end


end

event_scheduling/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
end

def create
  user = User.authenticate(params[:username], params[:password])
  # binding.pry
  if user
    session[:user_id] = user.id
    redirect_to schedule_path, :notice => "Logged in!"
  else
    flash.now.alert = "Invalid username or password"
    render "new"
  end
end

def destroy
  session[:user_id] = nil
  redirect_to root_url, :notice => "Logged out!"
end
end

event_scheduling/app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
  @user = User.new
end

def create
  @user = User.new(user_params)
  if @user.save
    redirect_to log_in_path, :notice => "Signed in!"
  else
    render "new"
  end
end

private

def user_params
params.require(:user).permit(:firstname,:lastname,:username,:email,:ph_no,:password,:password_confirmation)
end
end

event_scheduling/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

event_scheduling/app/helpers/application_helper.rb
module ApplicationHelper
end

event_scheduling/app/helpers/event_schedules_helper.rb
module EventSchedulesHelper
end

event_scheduling/app/helpers/events_helper.rb
module EventsHelper
end

event_scheduling/app/helpers/sessions_helper.rb
module SessionsHelper
end

event_scheduling/app/helpers/users_helper.rb
module UsersHelper
end

event_scheduling/app/helpers/welcome_helper.rb
module WelcomeHelper
end

event_scheduling/app/views/event_schedules/edit.html.erb
<%if current_user.id == @schedule.owner_id %>

<%= form_for :schedule, url:schedule_update_path(@schedule), method: :put do |f|%>


<%= f.label :Enter_Event_name%>    <%= f.text_field :title %></br></br>
<%= f.label :Enter_Venue%>       <%= f.text_field :venue %></br></br>
<%= f.label :Enter_date%>       <%= f.text_field :date %></br></br>
<%= f.label :Enter_time %>           <%= f.text_field :time %></br></br>
<p><%= f.label :Enter_description%></br>    <%= f.text_area :description, size: "60x5" %></br></br></p>
<%= f.label :Invited_by %> </br>    
<%= current_user.username%> </br>
 </br>
<%= f.label :Select_invitee %> 
<%= f.label :Enter_Status%>  
<%= f.select :status, ['open', 'closed']%></br></br></br>
<%= f.submit :Submit,:class=>"btn" %>

<%end%>


<%else%>
<%= form_for :schedule, url:schedule_update_path(@schedule), method: :put do |f|%>


<%= f.label :Enter_Event_name%>    <%= f.text_field :title,:disabled=>true %></br></br>
<%= f.label :Enter_Venue%>       <%= f.text_field :venue,:disabled=>true  %></br></br>
<%= f.label :Enter_date%>       <%= f.text_field :date,:disabled=>true  %></br></br>
<%= f.label :Enter_time %>           <%= f.text_field :time,:disabled=>true  %></br></br>
<p><%= f.label :Enter_description%></br>    <%= f.text_area :description, size: "60x5" ,:disabled=>true %></br></br></p>
<%= f.label :Invited_by %> </br>    
<%= current_user.username%> </br>
 </br>
<%= f.label :Select_invitee %> 
<%= f.label :Enter_Status%>  
<%= f.select :status, ['open', 'closed']%></br></br></br>
<%= f.submit :Submit,:class=>"btn" %>

<%end%>

<%end%>

event_scheduling/app/views/event_schedules/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Case</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#"><h1>Event Scheduler</h1></a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li> <%= link_to "Sign_in", sign_up_path %><a href="sign_in"></a></li>
      <li> <%= link_to "log_out", new_session_path %><a href="log_out"></a></li>
    </ul>
  </div>
</nav>



<div class="container">
 <!-- Trigger the modal with a button -->
 <button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Create event</button>

 <!-- Modal -->
 <div class="modal fade" id="myModal" role="dialog">
   <div class="modal-dialog">
   
     <!-- Modal content-->
     <div class="modal-content">
       <div class="modal-header">
         <button type="button" class="close" data-dismiss="modal">&times;</button>
         <h4 class="modal-title">New Event</h4>
       </div>
       <div class="modal-body"><h1 align="center">Event list</h1>
<center>
<%= form_for :schedule do |f| %>
 
   <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
   <p>
    <%= f.label :venue %><br />
    <%= f.text_field :venue %>
  </p>
  <p>
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </p>
  <p>
    <%= f.label :time %><br />
    <%= f.text_field :time %>
  </p>
   <p>
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </p>
   <p>
    <%= f.label :invitees %><br />
    <%= f.text_field :invitees %>
  </p>
   <p>
   <%= f.select :status, ['open', 'closed']%>
  </p>

  <p class="button"><%= f.submit %></p>
<% end %>
</center>

      </div>
       <div class="modal-footer">
         <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
       </div>
     </div>
 </div>
</div>
</div>


<div class="row">
   <div class="col-xs-6">
<% @schedules.each do |schedule| %>

   <div class="row" style="background-color:#D3D3D3  ; margin:5px; padding:20px">
   <label style="color:green">Schedule:</label><label> <%= schedule.title %></label><br>
   <label>Description: <%= schedule.description %></label>


<%= link_to 'edit event', schedule_edit_path(schedule) %>
<div class="container">
<!-- <h2>Modal Example</h2> -->
<!-- Trigger the modal with a button -->
<a  data-toggle="modal" data-target="#myModal2">Participents</a>

<!-- Modal -->
<div class="modal fade" id="myModal2" role="dialog">
  <div class="modal-dialog">
  
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">list of participants</h4>
      </div>
      <div class="modal-body">


      <% @users.each do |user| %>
      <%= user.firstname %>
      <% end %>
        <!-- <p>Some text in the modal.</p> -->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
    
  </div>
</div>

</div>      

   </div>
<% end %>

</div>
<div class="col-xs-6">
   <!-- adsff -->
   </div>
</div>

event_scheduling/app/views/layouts/application.html.erb
  

    <%= yield %>

    <footer style="background-color:#c8c9ce  ">
   <!-- =========================================================================  -->



  <div class="row" align="center">
  
    <p><a href="">BLOG &middot;</a><a href="">CONTACT</a>&copy; 2016 Company, Inc. &middot;<a href="#">Privacy</a> &middot; <a href="#">Terms</a>
    <address>
        EventScheduler
        
      </address>
      </p>
      </div>
      <div class="col-lg-4">
  
  </div>
      </footer>

</body>
</html>

event_scheduling/app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Case</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#"><h1>Event Scheduler</h1></a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li> <%= link_to "Sign_in", sign_up_path %><a href="sign_in"></a></li>
      <li> <%= link_to "log_in", log_in_path %><a href="log_in"></a></li>
    </ul>
  </div>
</nav>




<h1 align="center">Sign Up</h1>
<center>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
   <p>
    <%= f.label :firstname %><br />
    <%= f.text_field :firstname %>
  </p>
   <p>
    <%= f.label :lastname %><br />
    <%= f.text_field :lastname %>
  </p>
  <p>
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
   <p>
    <%= f.label :ph_no %><br />
    <%= f.text_field :ph_no %>
  </p>
   <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
   <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>

  <p class="button"><%= f.submit %></p>
<% end %>
</center>

event_scheduling/app/views/welcome/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Case</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#"><h1>Event Scheduler</h1></a>
    </div>
    <ul class="nav navbar-nav navbar-right">
      <li> <%= link_to "Sign_in", sign_up_path %><a href="sign_in"></a></li>
      <li> <%= link_to "log_in", log_in_path %><a href="log_in"></a></li>
    </ul>
  </div>
</nav>



<div class="container">
	<img src="../assets/1.jpg" class="img-rounded" alt="Cinque Terre" width="304">
</div>